
server:
  port: 8092

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratings_db

rabbitmq:
  host: localhost
  virtualhost: /
  port: 15672
  username: guest
  password: guest
  exchange: rabbitmq.exchange
  queue: rabbitmq.queue
  routingkey: rabbitmq.routingkey
  reply:
    timeout: 60000
  concurrent:
    consumers: 1  # dejar en 1 ya que aumentarlo lee mas de una vez el mismo mensaje
  max:
    concurrent:
      consumers: 2